I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/abs/humanite/naissance.rpy", line 71, in script
    $ genererPhilippe(situation_, traits_)
  File "game/abs/humanite/naissance.rpy", line 71, in <module>
    $ genererPhilippe(situation_, traits_)
NameError: name 'genererPhilippe' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/abs/humanite/naissance.rpy", line 71, in script
    $ genererPhilippe(situation_, traits_)
  File "renpy/ast.py", line 922, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2218, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/abs/humanite/naissance.rpy", line 71, in <module>
    $ genererPhilippe(situation_, traits_)
NameError: name 'genererPhilippe' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.4.1439
destinPhilippeAuguste 1.0
Sun Jul 25 20:18:10 2021
